apiVersion: v2
name: gitlab-mr-conform
description: A Helm chart for GitLab MR Conform Bot
type: application
version: 0.0.0
appVersion: 0.1.0
keywords:
  - gitlab
  - bot
  - merge-request
home: https://github.com/chrxmvtik/gitlab-mr-conform
maintainers:
  - name: chrxmvtik
